services:
  kops:
    image: clertonraf/kops-docker:latest
    platform: linux/amd64
    container_name: kops
    ports:
      - '${HTTP_PORT:-8080}:9090'
      - '${HTTPS_PORT:-443}:443'
    volumes:
      - ${LICENSE_FILE}:/opt/kops/kops.lic
