name: publish

on: [push]

jobs:
  publish-kops-docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      attestations: write
      deployments: write
    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses:  docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}

      - name: Build the kops-docker Docker image
        run: docker build . --tag ghcr.io/clertonraf/kops-docker:latest

      - name: Run docker image
        run: docker run ghcr.io/clertonraf/kops-docker:latest

      - name: Push docker image
        run: docker push ghcr.io/clertonraf/kops-docker:latest
