name: publish

on: [push]

jobs:
  publish-kops-docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      attestations: write
      deployments: write
    steps:
      - uses: actions/checkout@v4.1.7

      - name: Docker
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the clertonraf/kops-docker Docker image
        run: docker build . --tag clertonraf/kops-docker:latest

      - name: Run docker image
        run: docker run clertonraf/kops-docker:latest

      - name: Push docker image
        run: docker push clertonraf/kops-docker:latest
